
//** List types of mutations*/
export default {
    SET_USER: 'SET_USER',
    ADD_TODO: 'ADD_TODO',
    DELETE_TODO: 'DELETE_TODO',
    DELETE_ALL: 'DELETE_ALL',
    CHANGE_TODO_STATUS: 'CHANGE_TODO_STATUS',
    SELECT_ALL_TODO: 'SELECT_ALL_TODO',
    CHANGE_TODO_TITLE: 'CHANGE_TODO_TITLE',
    SET_TODOS: 'SET_TODOS'
}